### PR TITLE
Update projectId when already analyzed

### PR DESCRIPTION
**Pull request by helias22**
### Change types

- [x] Non-breaking change
- [x] Front end change

### Testing
- [ ] I have added testing to this PR

### CODE REVIEW

**Review by WeissSa — CHANGES_REQUESTED** [review]
With my PR merged this might required you to change the implementation for star/flag functionality again. Can you rebase to main and double check?

**Review by helias22 — COMMENTED** [review]
I merged main. Seems to be working but you can check if you're looking for a specific functionality.

**Review by WeissSa — APPROVED** [review]
Looks great! I QAd and it all worked nicely. Is there any testing that you think makes sense to add?

**Review by WeissSa — CHANGES_REQUESTED** [review]
I'm still getting the bug where once I click the merge checkbox, look at analysis
Go back then look at unmerged analysis
Then I cannot go back to merged analysis

**Review by WeissSa — APPROVED** [review]
I trolled myself this is great. Back to my testing comment.

**Review by williamyao27 — APPROVED** [review]
QA looks good to me. Code looks a bit cleaner too. Nice!

**Review by WeissSa — APPROVED** [review]
pokemon(1)

**Pull request merged**
