### PR TITLE
Adding logo to main page title

### PR DESCRIPTION
**Pull request by KayleeLChan**
## Pull Request Summary

Added svg bestflow icon to title on main page.

### Change types

- [x] Non-breaking change
- [x] Front end change

## Questions

Sadly, the centering for this thing was once again a real pain, so I used breakpoints to adjust it between monitor sizes. Please try loading it onto your screens and if you have multiple, move the window in between your screens to see if the title stays centered relatively OK! Thanks :) 👍

### CODE REVIEW

**Review by emilylwan — APPROVED** [review]
LGTM!

**Review by williamyao27 — APPROVED** [review]
A note on using Icon component:

For standalone svgs, you don't need to use the Icon component bc it actually requires more (but possibly more readable?) code. Its currently implementation is also designed for square-shaped icons that fit in buttons without much modification, so it might feel limiting if you are trying to artistically add the title. But it's all good, honestly I'm happy if you found a way to make use of Icon.jsx! It looks great on my end.

**Review by williamyao27 — CHANGES_REQUESTED** [review]
fix horizontal scroll bar

**Review by WeissSa — APPROVED** [review]
Awesome

**Review by williamyao27 — APPROVED** [review]
lgtgmtgltmgltgm

**Pull request merged**
